/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicProfileRouteImport } from './routes/api/public/profile'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicSubmissionsSubmitRouteImport } from './routes/api/public/submissions/submit'
import { Route as ApiPublicSubmissionsHistoryRouteImport } from './routes/api/public/submissions/history'
import { Route as ApiPublicJobsRetryHubspotRouteImport } from './routes/api/public/jobs/retry-hubspot'
import { Route as ApiPublicBillingPaymentsWebhookRouteImport } from './routes/api/public/billing/payments-webhook'
import { Route as ApiPublicBillingCreatePortalSessionRouteImport } from './routes/api/public/billing/create-portal-session'
import { Route as ApiPublicBillingCreateCheckoutRouteImport } from './routes/api/public/billing/create-checkout'
import { Route as ApiPublicBillingCheckSubscriptionRouteImport } from './routes/api/public/billing/check-subscription'
import { Route as ApiPublicAuthSessionRouteImport } from './routes/api/public/auth/session'
import { Route as ApiPublicAdminImportLegacyUsersRouteImport } from './routes/api/public/admin/import-legacy-users'
import { Route as ApiPublicAdminImportLegacySubmissionsRouteImport } from './routes/api/public/admin/import-legacy-submissions'
import { Route as ApiPublicAdminBootstrapHubspotSchemaRouteImport } from './routes/api/public/admin/bootstrap-hubspot-schema'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProfileRoute = ApiPublicProfileRouteImport.update({
  id: '/api/public/profile',
  path: '/api/public/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmissionsSubmitRoute =
  ApiPublicSubmissionsSubmitRouteImport.update({
    id: '/api/public/submissions/submit',
    path: '/api/public/submissions/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubmissionsHistoryRoute =
  ApiPublicSubmissionsHistoryRouteImport.update({
    id: '/api/public/submissions/history',
    path: '/api/public/submissions/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsRetryHubspotRoute =
  ApiPublicJobsRetryHubspotRouteImport.update({
    id: '/api/public/jobs/retry-hubspot',
    path: '/api/public/jobs/retry-hubspot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPaymentsWebhookRoute =
  ApiPublicBillingPaymentsWebhookRouteImport.update({
    id: '/api/public/billing/payments-webhook',
    path: '/api/public/billing/payments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingCreatePortalSessionRoute =
  ApiPublicBillingCreatePortalSessionRouteImport.update({
    id: '/api/public/billing/create-portal-session',
    path: '/api/public/billing/create-portal-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingCreateCheckoutRoute =
  ApiPublicBillingCreateCheckoutRouteImport.update({
    id: '/api/public/billing/create-checkout',
    path: '/api/public/billing/create-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingCheckSubscriptionRoute =
  ApiPublicBillingCheckSubscriptionRouteImport.update({
    id: '/api/public/billing/check-subscription',
    path: '/api/public/billing/check-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSessionRoute = ApiPublicAuthSessionRouteImport.update({
  id: '/api/public/auth/session',
  path: '/api/public/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminImportLegacyUsersRoute =
  ApiPublicAdminImportLegacyUsersRouteImport.update({
    id: '/api/public/admin/import-legacy-users',
    path: '/api/public/admin/import-legacy-users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminImportLegacySubmissionsRoute =
  ApiPublicAdminImportLegacySubmissionsRouteImport.update({
    id: '/api/public/admin/import-legacy-submissions',
    path: '/api/public/admin/import-legacy-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBootstrapHubspotSchemaRoute =
  ApiPublicAdminBootstrapHubspotSchemaRouteImport.update({
    id: '/api/public/admin/bootstrap-hubspot-schema',
    path: '/api/public/admin/bootstrap-hubspot-schema',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/profile': typeof ApiPublicProfileRoute
  '/api/public/admin/bootstrap-hubspot-schema': typeof ApiPublicAdminBootstrapHubspotSchemaRoute
  '/api/public/admin/import-legacy-submissions': typeof ApiPublicAdminImportLegacySubmissionsRoute
  '/api/public/admin/import-legacy-users': typeof ApiPublicAdminImportLegacyUsersRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/billing/check-subscription': typeof ApiPublicBillingCheckSubscriptionRoute
  '/api/public/billing/create-checkout': typeof ApiPublicBillingCreateCheckoutRoute
  '/api/public/billing/create-portal-session': typeof ApiPublicBillingCreatePortalSessionRoute
  '/api/public/billing/payments-webhook': typeof ApiPublicBillingPaymentsWebhookRoute
  '/api/public/jobs/retry-hubspot': typeof ApiPublicJobsRetryHubspotRoute
  '/api/public/submissions/history': typeof ApiPublicSubmissionsHistoryRoute
  '/api/public/submissions/submit': typeof ApiPublicSubmissionsSubmitRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/profile': typeof ApiPublicProfileRoute
  '/api/public/admin/bootstrap-hubspot-schema': typeof ApiPublicAdminBootstrapHubspotSchemaRoute
  '/api/public/admin/import-legacy-submissions': typeof ApiPublicAdminImportLegacySubmissionsRoute
  '/api/public/admin/import-legacy-users': typeof ApiPublicAdminImportLegacyUsersRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/billing/check-subscription': typeof ApiPublicBillingCheckSubscriptionRoute
  '/api/public/billing/create-checkout': typeof ApiPublicBillingCreateCheckoutRoute
  '/api/public/billing/create-portal-session': typeof ApiPublicBillingCreatePortalSessionRoute
  '/api/public/billing/payments-webhook': typeof ApiPublicBillingPaymentsWebhookRoute
  '/api/public/jobs/retry-hubspot': typeof ApiPublicJobsRetryHubspotRoute
  '/api/public/submissions/history': typeof ApiPublicSubmissionsHistoryRoute
  '/api/public/submissions/submit': typeof ApiPublicSubmissionsSubmitRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/profile': typeof ApiPublicProfileRoute
  '/api/public/admin/bootstrap-hubspot-schema': typeof ApiPublicAdminBootstrapHubspotSchemaRoute
  '/api/public/admin/import-legacy-submissions': typeof ApiPublicAdminImportLegacySubmissionsRoute
  '/api/public/admin/import-legacy-users': typeof ApiPublicAdminImportLegacyUsersRoute
  '/api/public/auth/session': typeof ApiPublicAuthSessionRoute
  '/api/public/billing/check-subscription': typeof ApiPublicBillingCheckSubscriptionRoute
  '/api/public/billing/create-checkout': typeof ApiPublicBillingCreateCheckoutRoute
  '/api/public/billing/create-portal-session': typeof ApiPublicBillingCreatePortalSessionRoute
  '/api/public/billing/payments-webhook': typeof ApiPublicBillingPaymentsWebhookRoute
  '/api/public/jobs/retry-hubspot': typeof ApiPublicJobsRetryHubspotRoute
  '/api/public/submissions/history': typeof ApiPublicSubmissionsHistoryRoute
  '/api/public/submissions/submit': typeof ApiPublicSubmissionsSubmitRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/manifest'
    | '/api/public/profile'
    | '/api/public/admin/bootstrap-hubspot-schema'
    | '/api/public/admin/import-legacy-submissions'
    | '/api/public/admin/import-legacy-users'
    | '/api/public/auth/session'
    | '/api/public/billing/check-subscription'
    | '/api/public/billing/create-checkout'
    | '/api/public/billing/create-portal-session'
    | '/api/public/billing/payments-webhook'
    | '/api/public/jobs/retry-hubspot'
    | '/api/public/submissions/history'
    | '/api/public/submissions/submit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/manifest'
    | '/api/public/profile'
    | '/api/public/admin/bootstrap-hubspot-schema'
    | '/api/public/admin/import-legacy-submissions'
    | '/api/public/admin/import-legacy-users'
    | '/api/public/auth/session'
    | '/api/public/billing/check-subscription'
    | '/api/public/billing/create-checkout'
    | '/api/public/billing/create-portal-session'
    | '/api/public/billing/payments-webhook'
    | '/api/public/jobs/retry-hubspot'
    | '/api/public/submissions/history'
    | '/api/public/submissions/submit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/docs'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/manifest'
    | '/api/public/profile'
    | '/api/public/admin/bootstrap-hubspot-schema'
    | '/api/public/admin/import-legacy-submissions'
    | '/api/public/admin/import-legacy-users'
    | '/api/public/auth/session'
    | '/api/public/billing/check-subscription'
    | '/api/public/billing/create-checkout'
    | '/api/public/billing/create-portal-session'
    | '/api/public/billing/payments-webhook'
    | '/api/public/jobs/retry-hubspot'
    | '/api/public/submissions/history'
    | '/api/public/submissions/submit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicProfileRoute: typeof ApiPublicProfileRoute
  ApiPublicAdminBootstrapHubspotSchemaRoute: typeof ApiPublicAdminBootstrapHubspotSchemaRoute
  ApiPublicAdminImportLegacySubmissionsRoute: typeof ApiPublicAdminImportLegacySubmissionsRoute
  ApiPublicAdminImportLegacyUsersRoute: typeof ApiPublicAdminImportLegacyUsersRoute
  ApiPublicAuthSessionRoute: typeof ApiPublicAuthSessionRoute
  ApiPublicBillingCheckSubscriptionRoute: typeof ApiPublicBillingCheckSubscriptionRoute
  ApiPublicBillingCreateCheckoutRoute: typeof ApiPublicBillingCreateCheckoutRoute
  ApiPublicBillingCreatePortalSessionRoute: typeof ApiPublicBillingCreatePortalSessionRoute
  ApiPublicBillingPaymentsWebhookRoute: typeof ApiPublicBillingPaymentsWebhookRoute
  ApiPublicJobsRetryHubspotRoute: typeof ApiPublicJobsRetryHubspotRoute
  ApiPublicSubmissionsHistoryRoute: typeof ApiPublicSubmissionsHistoryRoute
  ApiPublicSubmissionsSubmitRoute: typeof ApiPublicSubmissionsSubmitRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profile': {
      id: '/api/public/profile'
      path: '/api/public/profile'
      fullPath: '/api/public/profile'
      preLoaderRoute: typeof ApiPublicProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions/submit': {
      id: '/api/public/submissions/submit'
      path: '/api/public/submissions/submit'
      fullPath: '/api/public/submissions/submit'
      preLoaderRoute: typeof ApiPublicSubmissionsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions/history': {
      id: '/api/public/submissions/history'
      path: '/api/public/submissions/history'
      fullPath: '/api/public/submissions/history'
      preLoaderRoute: typeof ApiPublicSubmissionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/retry-hubspot': {
      id: '/api/public/jobs/retry-hubspot'
      path: '/api/public/jobs/retry-hubspot'
      fullPath: '/api/public/jobs/retry-hubspot'
      preLoaderRoute: typeof ApiPublicJobsRetryHubspotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/payments-webhook': {
      id: '/api/public/billing/payments-webhook'
      path: '/api/public/billing/payments-webhook'
      fullPath: '/api/public/billing/payments-webhook'
      preLoaderRoute: typeof ApiPublicBillingPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/create-portal-session': {
      id: '/api/public/billing/create-portal-session'
      path: '/api/public/billing/create-portal-session'
      fullPath: '/api/public/billing/create-portal-session'
      preLoaderRoute: typeof ApiPublicBillingCreatePortalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/create-checkout': {
      id: '/api/public/billing/create-checkout'
      path: '/api/public/billing/create-checkout'
      fullPath: '/api/public/billing/create-checkout'
      preLoaderRoute: typeof ApiPublicBillingCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/check-subscription': {
      id: '/api/public/billing/check-subscription'
      path: '/api/public/billing/check-subscription'
      fullPath: '/api/public/billing/check-subscription'
      preLoaderRoute: typeof ApiPublicBillingCheckSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/session': {
      id: '/api/public/auth/session'
      path: '/api/public/auth/session'
      fullPath: '/api/public/auth/session'
      preLoaderRoute: typeof ApiPublicAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/import-legacy-users': {
      id: '/api/public/admin/import-legacy-users'
      path: '/api/public/admin/import-legacy-users'
      fullPath: '/api/public/admin/import-legacy-users'
      preLoaderRoute: typeof ApiPublicAdminImportLegacyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/import-legacy-submissions': {
      id: '/api/public/admin/import-legacy-submissions'
      path: '/api/public/admin/import-legacy-submissions'
      fullPath: '/api/public/admin/import-legacy-submissions'
      preLoaderRoute: typeof ApiPublicAdminImportLegacySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/bootstrap-hubspot-schema': {
      id: '/api/public/admin/bootstrap-hubspot-schema'
      path: '/api/public/admin/bootstrap-hubspot-schema'
      fullPath: '/api/public/admin/bootstrap-hubspot-schema'
      preLoaderRoute: typeof ApiPublicAdminBootstrapHubspotSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicProfileRoute: ApiPublicProfileRoute,
  ApiPublicAdminBootstrapHubspotSchemaRoute:
    ApiPublicAdminBootstrapHubspotSchemaRoute,
  ApiPublicAdminImportLegacySubmissionsRoute:
    ApiPublicAdminImportLegacySubmissionsRoute,
  ApiPublicAdminImportLegacyUsersRoute: ApiPublicAdminImportLegacyUsersRoute,
  ApiPublicAuthSessionRoute: ApiPublicAuthSessionRoute,
  ApiPublicBillingCheckSubscriptionRoute:
    ApiPublicBillingCheckSubscriptionRoute,
  ApiPublicBillingCreateCheckoutRoute: ApiPublicBillingCreateCheckoutRoute,
  ApiPublicBillingCreatePortalSessionRoute:
    ApiPublicBillingCreatePortalSessionRoute,
  ApiPublicBillingPaymentsWebhookRoute: ApiPublicBillingPaymentsWebhookRoute,
  ApiPublicJobsRetryHubspotRoute: ApiPublicJobsRetryHubspotRoute,
  ApiPublicSubmissionsHistoryRoute: ApiPublicSubmissionsHistoryRoute,
  ApiPublicSubmissionsSubmitRoute: ApiPublicSubmissionsSubmitRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
